import { Supplier } from './suppliers-column';

export const suppliers: Supplier[] = [
  {
    id: '1',
    name: 'Global Tech Supplies',
    address: '123 Tech Lane, San Francisco, CA',
    phoneNumber: '555-1234',
    email: 'info@globaltech.com',
  },
  {
    id: '2',
    name: 'Green Earth Organics',
    address: '456 Eco Drive, Portland, OR',
    phoneNumber: '555-2345',
    email: 'contact@greenearth.com',
  },
  {
    id: '3',
    name: 'Oceanic Foods',
    address: '789 Sea Street, Miami, FL',
    phoneNumber: '555-3456',
    email: 'sales@oceanicfoods.com',
  },
  {
    id: '4',
    name: 'Mountain Gear Co.',
    address: '101 Alpine Way, Denver, CO',
    phoneNumber: '555-4567',
    email: 'support@mountaingear.com',
  },
  {
    id: '5',
    name: 'Urban Fashion Apparel',
    address: '202 Style Blvd, New York, NY',
    phoneNumber: '555-5678',
    email: 'help@urbanfashion.com',
  },
  {
    id: '6',
    name: 'Bright Light Electronics',
    address: '303 Glow Street, Las Vegas, NV',
    phoneNumber: '555-6789',
    email: 'service@brightlight.com',
  },
  {
    id: '7',
    name: 'Pure Water Solutions',
    address: '404 Clear Spring Rd, Austin, TX',
    phoneNumber: '555-7890',
    email: 'contact@purewater.com',
  },
  {
    id: '8',
    name: 'Countryside Dairy',
    address: '505 Farm Lane, Madison, WI',
    phoneNumber: '555-8901',
    email: 'info@countrydairy.com',
  },
  {
    id: '9',
    name: 'Heritage Books Publishing',
    address: '606 Library Ave, Boston, MA',
    phoneNumber: '555-9012',
    email: 'support@heritagebooks.com',
  },
  {
    id: '10',
    name: 'Summit Outdoor Equipment',
    address: '707 Peak Path, Salt Lake City, UT',
    phoneNumber: '555-0123',
    email: 'sales@summitoutdoor.com',
  },
  {
    id: '11',
    name: 'Golden Grain Foods',
    address: '808 Harvest Rd, Omaha, NE',
    phoneNumber: '555-1235',
    email: 'info@goldengrain.com',
  },
  {
    id: '12',
    name: 'Blue Sky Airlines',
    address: '909 Cloud Street, Atlanta, GA',
    phoneNumber: '555-2346',
    email: 'contact@bluesky.com',
  },
  {
    id: '13',
    name: 'Pioneer Tools',
    address: '1010 Forge Lane, Pittsburgh, PA',
    phoneNumber: '555-3457',
    email: 'support@pioneertools.com',
  },
  {
    id: '14',
    name: 'Crystal Clear Optics',
    address: '1111 Lens Way, Rochester, NY',
    phoneNumber: '555-4568',
    email: 'service@crystaloptics.com',
  },
  {
    id: '15',
    name: "Nature's Best Cosmetics",
    address: '1212 Beauty Ave, Los Angeles, CA',
    phoneNumber: '555-5679',
    email: 'info@naturesbest.com',
  },
  {
    id: '16',
    name: 'Ironclad Security',
    address: '1313 Safe Drive, Washington, DC',
    phoneNumber: '555-6780',
    email: 'help@ironclad.com',
  },
  {
    id: '17',
    name: 'Fresh Farm Produce',
    address: '1414 Orchard Rd, Fresno, CA',
    phoneNumber: '555-7891',
    email: 'contact@freshfarm.com',
  },
  {
    id: '18',
    name: 'Starlight Events',
    address: '1515 Celebration Blvd, Orlando, FL',
    phoneNumber: '555-8902',
    email: 'info@starlightevents.com',
  },
  {
    id: '19',
    name: 'Aqua Marine Supplies',
    address: '1616 Ocean View, Seattle, WA',
    phoneNumber: '555-9013',
    email: 'support@aquamarine.com',
  },
  {
    id: '20',
    name: 'Bold Brews Coffee',
    address: '1717 Bean Street, Portland, OR',
    phoneNumber: '555-0124',
    email: 'sales@boldbrews.com',
  },
  {
    id: '21',
    name: 'Tech Innovate Solutions',
    address: '1818 Circuit Rd, San Jose, CA',
    phoneNumber: '555-1236',
    email: 'info@techinnovate.com',
  },
  {
    id: '22',
    name: 'Eco-Friendly Packaging',
    address: '1919 Green Way, Boulder, CO',
    phoneNumber: '555-2347',
    email: 'contact@ecopack.com',
  },
  {
    id: '23',
    name: 'Heritage Furniture',
    address: '2020 Timberline, Asheville, NC',
    phoneNumber: '555-3458',
    email: 'support@heritagefurniture.com',
  },
  {
    id: '24',
    name: 'Sunrise Solar Tech',
    address: '2121 Sunbeam Ave, Phoenix, AZ',
    phoneNumber: '555-4569',
    email: 'service@sunsolar.com',
  },
  {
    id: '25',
    name: 'Metro Fitness Gear',
    address: '2222 Health St, Chicago, IL',
    phoneNumber: '555-5670',
    email: 'info@metrofitness.com',
  },
  {
    id: '26',
    name: 'Artisan Breads Co.',
    address: "2323 Baker's Way, San Diego, CA",
    phoneNumber: '555-6781',
    email: 'contact@artisanbreads.com',
  },
  {
    id: '27',
    name: 'NextGen Robotics',
    address: '2424 Future Drive, Austin, TX',
    phoneNumber: '555-7892',
    email: 'support@nextgenrobotics.com',
  },
  {
    id: '28',
    name: 'Vintage Vinyl Records',
    address: '2525 Retro Lane, Nashville, TN',
    phoneNumber: '555-8903',
    email: 'info@vintagevinyl.com',
  },
  {
    id: '29',
    name: 'Pure Air Filters',
    address: '2626 Breeze Blvd, Minneapolis, MN',
    phoneNumber: '555-9014',
    email: 'sales@pureair.com',
  },
  {
    id: '30',
    name: 'Luxe Leather Goods',
    address: '2727 Chic Street, Dallas, TX',
    phoneNumber: '555-0125',
    email: 'contact@luxeleather.com',
  },
];
